name: docs

on:
  # 当 push 到 main 分支时触发部署（确保你的默认分支设置为 main）
  push:
    branches: [master]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 安装依赖
        run: npm install --frozen-lockfile
        # 注意：确保你有一个 package-lock.json 文件来与 --frozen-lockfile 一起使用

      - name: 构建 VuePress 站点
        run: npm run docs:build
        # 确保你的 package.json 中有一个名为 "docs:build" 的脚本

      - name: 部署到 GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}